# Generated by Django 3.1.2 on 2020-10-21 07:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=100)),
                ('entity_id', models.CharField(db_index=True, max_length=100)),
                ('entity_obj', models.JSONField()),
            ],
            options={
                'verbose_name': 'Approval Entity',
                'verbose_name_plural': 'Approval Entitys',
                'db_table': 'approval_entity',
            },
        ),
        migrations.CreateModel(
            name='ApprovalPending',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.IntegerField()),
                ('status', models.BooleanField()),
                ('approval_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_pending_entity', to='approval_engine.approvalentity')),
            ],
            options={
                'verbose_name': 'Approval Pending',
                'verbose_name_plural': 'Approval Pendings',
                'db_table': 'approval_pending',
            },
        ),
    ]
