# Generated by Django 3.1.2 on 2020-10-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_engine', '0002_auto_20201021_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalpending',
            name='hiring_manager',
        ),
        migrations.AddField(
            model_name='approvalpending',
            name='approver_id',
            field=models.CharField(db_index=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
